name: Tests

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Setup docker infra
        run: |
          docker network create spec_default
          docker-compose -f ./spec/docker-compose.yml up -d --build
          docker ps -a
          i="0"; while true; do echo Checking...; echo $(docker logs spec_puppet_1 --tail 10) | grep -q 'Puppet Server has successfully started' && break; if [ $i -gt 90 ]; then exit 1; fi; sleep 1; i=$[$i+1]; done;
          docker exec spec_puppet_1 puppetserver ca generate --certname aceserver --subject-alt-names 'puppet,localhost,aceserver,ace_aceserver_1,spec_puppetserver_1,ace_server,puppet_server,spec_aceserver_1,puppetdb,spec_puppetdb_1,0.0.0.0'
          sudo chmod a+rx -R spec/volumes/
      - name: Run tests
        run: bundle exec rake
